import type { Metadata } from "next";
import { Josefin_Sans, Anton } from "next/font/google";
import "../globals.css";
import Navbar from "./Components/Navbar";
import Footer from "./Components/Footer";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import "swiper/css";
import "swiper/css/pagination";

const josefin = Josefin_Sans({
  subsets: ["latin"],
  variable: "--font-josefin",
});

const anton = Anton({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-anton",
});

export const metadata: Metadata = {
  title: "Mosaic Biz Hub",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="with-fixed-header">
      <body
        className={`${josefin.variable} ${anton.variable} antialiased min-h-screen w-screen`}
      >
        <Navbar/>
        {children}
        <ToastContainer position="top-right" autoClose={3000} />
        <Footer/>
      </body>
    </html>
  );
}
