import type { Metadata } from "next";
import "../globals.css";
import AnnouncementBar from "./Components/AnnouncementBar";
import Navbar from "./Components/Navbar";
import Footer from "./Components/Footer";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import "swiper/css";
import "swiper/css/pagination";
import { fontVariables } from "@/lib/fonts";

export const metadata: Metadata = {
  title: "Mosaic Biz Hub",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="with-fixed-header">
      <body className={`${fontVariables} market-page antialiased min-h-screen w-screen`}>
        <AnnouncementBar />
        <Navbar />
        {children}
        <ToastContainer position="top-right" autoClose={3000} />
        <Footer />
      </body>
    </html>
  );
}
